import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import type { BacktestRun } from '@quantlab/shared-types';
import { TIMEFRAME_LABELS } from '@quantlab/shared-types';
import { useBacktestsList } from '../features/backtests/useBacktests';

const STATUS_STYLES: Record<string, { label: string; cls: string }> = {
  COMPLETED: { label: 'Completed', cls: 'bg-profit/10 text-profit border-profit/20'    },
  FAILED:    { label: 'Failed',    cls: 'bg-loss/10 text-loss border-loss/20'          },
  RUNNING:   { label: 'Running',   cls: 'bg-warning/10 text-warning border-warning/20' },
  PENDING:   { label: 'Pending',   cls: 'bg-zinc-700/30 text-zinc-400 border-zinc-700' },
};

function StatusBadge({ status }: { status: string }) {
  const { label, cls } = STATUS_STYLES[status] ?? { label: status, cls: 'bg-zinc-800 text-zinc-400 border-zinc-700' };
  return (
    <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${cls}`}>
      {label}
    </span>
  );
}

function ReturnCell({ value }: { value: number | null }) {
  if (value === null) return <span className="font-mono text-zinc-600">—</span>;
  const positive = value >= 0;
  return (
    <span className={`font-mono font-semibold tabular-nums ${positive ? 'text-profit' : 'text-loss'}`}>
      {positive ? '+' : ''}{value.toFixed(2)}%
    </span>
  );
}

export function BacktestsPage() {
  const { data: runs, isLoading, isError } = useBacktestsList();
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [activeTab, setActiveTab] = useState<'examples' | 'mine'>('examples');
  const navigate = useNavigate();

  function toggleSelected(id: string): void {
    setSelectedIds((current) => {
      const next = new Set(current);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  }

  function handleCompare(): void {
    navigate(`/backtests/compare?ids=${Array.from(selectedIds).join(',')}`);
  }

  const exampleRuns = runs?.filter((r) => r.isBuiltIn)  ?? [];
  const myRuns      = runs?.filter((r) => !r.isBuiltIn) ?? [];
  const displayed   = activeTab === 'examples' ? exampleRuns : myRuns;

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-zinc-100">Backtests</h1>
          <p className="mt-1 text-sm text-zinc-500">
            Explore example runs or view your own backtest history.
          </p>
        </div>
        <div className="flex items-center gap-2">
          {selectedIds.size >= 2 && (
            <button
              type="button"
              onClick={handleCompare}
              className="inline-flex items-center gap-2 rounded-md bg-accent-600 px-3.5 py-2 text-sm font-medium text-white transition-colors hover:bg-accent-700"
            >
              Compare ({selectedIds.size})
            </button>
          )}
          {selectedIds.size > 0 && selectedIds.size < 2 && (
            <span className="text-xs text-zinc-500">Select {2 - selectedIds.size} more to compare</span>
          )}
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-1 rounded-md border border-zinc-800 bg-zinc-900 p-0.5 w-fit">
        {(['examples', 'mine'] as const).map((tab) => (
          <button
            key={tab}
            type="button"
            onClick={() => setActiveTab(tab)}
            className={`rounded px-4 py-1.5 text-sm font-medium transition-colors duration-100 ${
              activeTab === tab ? 'bg-zinc-700 text-zinc-100' : 'text-zinc-500 hover:text-zinc-300'
            }`}
          >
            {tab === 'examples' ? `Example Runs (${exampleRuns.length})` : `My Backtests (${myRuns.length})`}
          </button>
        ))}
      </div>

      <p className="text-xs text-zinc-600">
        {activeTab === 'examples'
          ? 'Completed backtests generated by QuantLab\'s engine — shared by every account.'
          : 'Backtests you have run yourself. Select 2+ completed runs to compare.'}
      </p>

      {/* Loading */}
      {isLoading && (
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-12 animate-pulse rounded-lg bg-zinc-800/50" />
          ))}
        </div>
      )}

      {/* Error */}
      {isError && (
        <p className="text-sm text-red-400">Couldn&apos;t load backtests. Please refresh.</p>
      )}

      {/* Table */}
      {runs && (
        displayed.length === 0 ? (
          <div className="rounded-lg border border-dashed border-zinc-800 px-6 py-12 text-center">
            <p className="text-sm text-zinc-500">
              {activeTab === 'mine' ? "You haven't run any backtests yet." : 'No example backtests available.'}
            </p>
            {activeTab === 'mine' && (
              <Link to="/backtests/new" className="mt-3 inline-block text-sm font-medium text-zinc-400 hover:text-zinc-200 transition-colors">
                Run your first backtest →
              </Link>
            )}
          </div>
        ) : (
          <div className="overflow-x-auto rounded-lg border border-zinc-800">
            <table className="w-full min-w-[860px] text-left text-sm">
              <thead>
                <tr className="border-b border-zinc-800 bg-zinc-900/80">
                  <th className="px-3 py-2.5 text-xs font-medium uppercase tracking-wider text-zinc-600">
                    <span className="sr-only">Select</span>
                  </th>
                  <th className="px-3 py-2.5 text-xs font-medium uppercase tracking-wider text-zinc-600">Symbol</th>
                  <th className="px-3 py-2.5 text-xs font-medium uppercase tracking-wider text-zinc-600">Timeframe</th>
                  <th className="px-3 py-2.5 text-xs font-medium uppercase tracking-wider text-zinc-600">Period</th>
                  <th className="px-3 py-2.5 text-xs font-medium uppercase tracking-wider text-zinc-600">Status</th>
                  <th className="px-3 py-2.5 text-right text-xs font-medium uppercase tracking-wider text-zinc-600">Return</th>
                  <th className="px-3 py-2.5 text-xs font-medium uppercase tracking-wider text-zinc-600">Run Date</th>
                  <th className="px-4 py-2.5 text-right text-xs font-medium uppercase tracking-wider text-zinc-600">
                    <span className="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {displayed.map((run) => (
                  <BacktestRow
                    key={run.id}
                    run={run}
                    isSelected={selectedIds.has(run.id)}
                    onToggle={() => toggleSelected(run.id)}
                  />
                ))}
              </tbody>
            </table>
          </div>
        )
      )}
    </div>
  );
}

function BacktestRow({
  run,
  isSelected,
  onToggle,
}: {
  run: BacktestRun;
  isSelected: boolean;
  onToggle: () => void;
}) {
  return (
    <tr className={`border-b border-zinc-800/50 transition-colors duration-75 last:border-b-0 hover:bg-zinc-800/30 ${isSelected ? 'bg-zinc-800/20' : ''}`}>
      <td className="px-3 py-3">
        <input
          type="checkbox"
          checked={isSelected}
          onChange={onToggle}
          disabled={run.status !== 'COMPLETED'}
          aria-label={`Select ${run.symbol} for comparison`}
          className="h-3.5 w-3.5 accent-accent-500 disabled:cursor-not-allowed disabled:opacity-40"
        />
      </td>
      <td className="px-3 py-3">
        <Link to={`/backtests/${run.id}`} className="font-semibold text-zinc-100 hover:text-zinc-300 transition-colors">
          {run.symbol}
        </Link>
      </td>
      <td className="px-3 py-3 text-sm text-zinc-400">
        {TIMEFRAME_LABELS[run.timeframe] ?? run.timeframe}
      </td>
      <td className="px-3 py-3 text-sm text-zinc-500">
        {new Date(run.dateFrom).toLocaleDateString()} — {new Date(run.dateTo).toLocaleDateString()}
      </td>
      <td className="px-3 py-3">
        <StatusBadge status={run.status} />
      </td>
      <td className="px-3 py-3 text-right">
        <ReturnCell value={run.totalReturnPct} />
      </td>
      <td className="px-3 py-3 text-sm text-zinc-500">
        {new Date(run.createdAt).toLocaleDateString()}
      </td>
      <td className="px-4 py-3 text-right">
        <Link
          to={`/backtests/${run.id}`}
          className="inline-flex items-center rounded border border-amber-700/30 bg-transparent px-2.5 py-1 text-xs font-medium text-amber-500 transition-colors hover:border-amber-600/40 hover:text-amber-400 whitespace-nowrap"
        >
          View Analysis →
        </Link>
      </td>
    </tr>
  );
}
